- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_taps:
      - caskroom/cask
    homebrew_packages:
      - { name: readline }
      - { name: openssl }
      - { name: openssl, state: linked, install_options: force }
      - { name: python }
      - { name: ansible }
      - { name: coreutils }
      - { name: curl }
      - { name: git }
      - { name: macvim }
      - { name: mysql }
      - { name: rbenv }
      - { name: ruby-build }
      - { name: vim }
      - { name: wget }
    homebrew_cask_packages:
      - { name: chefdk }
      - { name: vagrant }
      - { name: virtualbox }
  tasks:
    - name: Tap homebrew repositories
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps
    - name: Update homebrew
      homebrew: update_homebrew=yes
    - name: Install packages
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages
      register: brew_result
    - name: Create directory to store homebrew package info
      file: path=brew_info state=directory
    - name: Store homebrew package info
      shell: brew info {{ item }} > brew_info/{{ item }}
      with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list
    - name: Install homebrew-cask
      homebrew: name=brew-cask state=latest
    - name: Install cask packages
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: homebrew_cask_packages
      register: cask_result
    - name: Create directory to store homebrew cask package info
      file: path=cask_info state=directory
    - name: Store homebrew cask package info
      shell: brew cask info {{ item }} > cask_info/{{ item }}
      with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list
    - name: Install vagrant plugins
      shell: vagrant plugin install {{ item }}
      with_items:
        - vagrant-berkshelf
        - vagrant-exec
        - vagrant-omnibus
    - name: Configure git
      command: git config --global {{ item }}
      with_items:
        - user.name "Shou Takenaka"
        - user.email sasaminn@gmail.com
        - core.editor vim
        - color.ui true
